dist: bionic
language: minimal

services:
  - docker

script:
  - "./gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.additional-build-args=--report-unsupported-elements-at-runtime,--allow-incomplete-classpath,-H:IncludeResources='.*yaml$',-H:Log=registerResource:"

after_success:
  - bash <(curl -s https://codecov.io/bash)
