dist: bionic
language: minimal

#services:
#  - docker
#
#script:
#  - "./gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.additional-build-args=--report-unsupported-elements-at-runtime,--allow-incomplete-classpath,-H:IncludeResources='.*yaml$',-H:Log=registerResource:"

jobs:
  include:
    - language: minimal
      name: Linux native image
      services:
        - docker
      script:
        - "./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.additional-build-args=--report-unsupported-elements-at-runtime,--allow-incomplete-classpath,-H:IncludeResources='.*yaml$',-H:Log=registerResource:"

    - language: java
      name: Jar
      jdk:
        - openjdk11
        - openjdk14
      script:
        - "./gradlew test quarkusBuild --uber-jar"
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - os: windows
      name: Windows native image
      language: shell
      env: JAVA_HOME="$HOME/.sdkman/candidates/java/current"
      before_install:
        - choco install zip unzip
        - choco install visualstudio2017-workload-vctools
        - curl -sL https://get.sdkman.io | bash
        - mkdir -p "$HOME/.sdkman/etc/"
        - echo sdkman_auto_answer=true > "$HOME/.sdkman/etc/config"
        - echo sdkman_auto_selfupdate=true >> "$HOME/.sdkman/etc/config"
        - "source $HOME/.sdkman/bin/sdkman-init.sh"
      install:
        - sdk install java 20.2.0.r11-grl
        - gu.cmd install native-image
        - native-image.cmd --version
      script:
        - "./gradlew quarkusBuild --uber-jar"
        - ./build.bat
        - cp /c/Windows/System32/VCRUNTIME140.dll .
        - zip kattlo.zip kattlo.exe VCRUNTIME140.dll

before_deploy:
  - mkdir release
  - cp build/kattlo-0.1.0-runner release/kattlo-linux-x86_64-${TRAVIS_TAG}
  - cp build/kattlo-0.1.0-runner.jar release/kattlo-${TRAVIS_TAG}.jar
  - zip kattlo-windows-x86_64-${TRAVIS_TAG}.zip kattlo.exe VCRUNTIME140.dll
  - mv kattlo-windows-x86_64-${TRAVIS_TAG}.zip release

deploy:
  provider: releases
  api_key:
    secure: "NpvLrF3p16HUQVdwUpQwtKocAVpPqt5EbdUVlE05+D0X070v5WVq0dxDqK+5gwLWhAos8P2lqKFrGW5P+DcmyiDXsNgJTdSmoDnDJVM4MYmX/r2xSDDKh0Z8NQP2X53EEQwkSQOOphg5w01+oLP3vqa3jIEjU5ErtRTF4N2GeIJqj7GLkYo7rnJQ++ETsBd8A5ILSd0sBIWoucsfjvkUZYNQIlL3QGQPo4irjlpUeeCKSw4/20n0pw1hbJiaPnAKYLSF5vyHNohX1jPY3Shbca7XW9n9kT7WR7IRoF3jL4MB/h9/Nz6iygwBBr5yOhr3zT0L0wOEPalpYEhFC4Fv55brB/9KWQgcydZNPFyMkX/ALVMvbxMESDIbqz+cOeLUK9EaH+S4QCk1KbVlEZYipEajcEd6mCKMnW7Ola5lvHZchVlKnUKeE0lKlGp5JBIPxdJbvPN6S4hXtiTRBUEMQ9FGYlIDF/Xb/XZ8k8q0OcEm7T2Cp4fzbndJwbaFObCmNaArK+uaWsx2uPyTY0ER9ZRtoJ3bXB1IZolvtpW1WUMHy8x2Wyg0+3DJugd7ARnmW1mFrKBcqUce6ogU5IRNrX8TuRaiKkvqWYJWQg53ZZOiWKcFFO+TMwojSFIU0pcd1IDx9rtzfdb5hlXEWdisYXPtsEmV9QnVZB7r9q5R1yU="
  file: release/*
  file_glob: true
  skip_cleanup: true
  draft: true
  on:
    tags: true
