#thanks to https://github.com/recursivecodes/simple-socket-fn-logger/blob/master/.github/workflows/simple-socket-fn-logger.yaml
name: release
on:
  push:
    tags:
      - "v*"
    branches:
      - 'master'

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Get Version Number
        run: |
          echo "::set-env name=VERSION_BUILD::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"
          echo "::set-env name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)"

      - name: Runnable Jar
        run: |
          ./gradlew test quarkusBuild --uber-jar
          cp build/kattlo-${{env.VERSION_BUILD}}-runner.jar build/kattlo-${{env.VERSION}}.jar

      - name: Publish JAR
        uses: actions/upload-artifact@v2-preview
        with:
          name: kattlo-${{env.VERSION}}.jar
          path: build/*.jar

      - name: Create Release
        if: contains(github.ref, 'v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}
          body: |
            Initial release
          draft: true
          prerelease: false

      - name: Upload Release Asset
        if: contains(github.ref, 'v')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: build/kattlo-${{env.VERSION}}.jar
          asset_name: kattlo-${{env.VERSION}}.jar
          asset_content_type: application/java-archive
